//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;


namespace Robotics.ZWave.Dimmer
{
    
    
    /// <summary>
    /// Zwavehousecontrols Contract
    /// </summary>
    public sealed class Contract
    {
        
        /// The Unique Contract Identifier for the Zwavehousecontrols service
        [DataMember]
        public const String Identifier = "http://house.robot/2008/04/zwavehousecontrols.html";
    }
}
