//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("DeviceController")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("DeviceController")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="DeviceController.Y2020.M01, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c131" +
    "bbd27e23e9e8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformDeviceController {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::DeviceController.Proxy.DeviceControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_Proxy_DeviceControllerState_TO_DeviceController_DeviceControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::DeviceController.DeviceControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_DeviceControllerState_TO_DeviceController_Proxy_DeviceControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::DeviceController.Proxy.ReceiveUpdatesRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_Proxy_ReceiveUpdatesRequest_TO_DeviceController_ReceiveUpdatesRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::DeviceController.ReceiveUpdatesRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_ReceiveUpdatesRequest_TO_DeviceController_Proxy_ReceiveUpdatesRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::DeviceController.Proxy.ReceiveNormalRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_Proxy_ReceiveNormalRequest_TO_DeviceController_ReceiveNormalRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::DeviceController.ReceiveNormalRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_ReceiveNormalRequest_TO_DeviceController_Proxy_ReceiveNormalRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::DeviceController.Proxy.ReceiveTriggeredRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_Proxy_ReceiveTriggeredRequest_TO_DeviceController_ReceiveTriggeredRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::DeviceController.ReceiveTriggeredRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_ReceiveTriggeredRequest_TO_DeviceController_Proxy_ReceiveTriggeredRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::DeviceController.Proxy.DeviceControllerStateRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_Proxy_DeviceControllerStateRequest_TO_DeviceController_DeviceControllerStateRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::DeviceController.DeviceControllerStateRequest), new global::Microsoft.Dss.Core.Attributes.Transform(DeviceController_DeviceControllerStateRequest_TO_DeviceController_Proxy_DeviceControllerStateRequest));
        }
        
        public static object DeviceController_Proxy_DeviceControllerState_TO_DeviceController_DeviceControllerState(object transformFrom) {
            global::DeviceController.DeviceControllerState target = new global::DeviceController.DeviceControllerState();
            global::DeviceController.Proxy.DeviceControllerState from = ((global::DeviceController.Proxy.DeviceControllerState)(transformFrom));
            target.Name = from.Name;
            target.Active = from.Active;
            return target;
        }
        
        public static object DeviceController_DeviceControllerState_TO_DeviceController_Proxy_DeviceControllerState(object transformFrom) {
            global::DeviceController.Proxy.DeviceControllerState target = new global::DeviceController.Proxy.DeviceControllerState();
            global::DeviceController.DeviceControllerState from = ((global::DeviceController.DeviceControllerState)(transformFrom));
            target.Name = from.Name;
            target.Active = from.Active;
            return target;
        }
        
        public static object DeviceController_Proxy_ReceiveUpdatesRequest_TO_DeviceController_ReceiveUpdatesRequest(object transformFrom) {
            global::DeviceController.ReceiveUpdatesRequest target = new global::DeviceController.ReceiveUpdatesRequest();
            global::DeviceController.Proxy.ReceiveUpdatesRequest from = ((global::DeviceController.Proxy.ReceiveUpdatesRequest)(transformFrom));
            target.Name = from.Name;
            target.Count = from.Count;
            return target;
        }
        
        public static object DeviceController_ReceiveUpdatesRequest_TO_DeviceController_Proxy_ReceiveUpdatesRequest(object transformFrom) {
            global::DeviceController.Proxy.ReceiveUpdatesRequest target = new global::DeviceController.Proxy.ReceiveUpdatesRequest();
            global::DeviceController.ReceiveUpdatesRequest from = ((global::DeviceController.ReceiveUpdatesRequest)(transformFrom));
            target.Name = from.Name;
            target.Count = from.Count;
            return target;
        }
        
        private static global::DeviceController.Proxy.ReceiveNormalRequest _cachedInstance0 = new global::DeviceController.Proxy.ReceiveNormalRequest();
        
        private static global::DeviceController.ReceiveNormalRequest _cachedInstance = new global::DeviceController.ReceiveNormalRequest();
        
        public static object DeviceController_Proxy_ReceiveNormalRequest_TO_DeviceController_ReceiveNormalRequest(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object DeviceController_ReceiveNormalRequest_TO_DeviceController_Proxy_ReceiveNormalRequest(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::DeviceController.Proxy.ReceiveTriggeredRequest _cachedInstance2 = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
        
        private static global::DeviceController.ReceiveTriggeredRequest _cachedInstance1 = new global::DeviceController.ReceiveTriggeredRequest();
        
        public static object DeviceController_Proxy_ReceiveTriggeredRequest_TO_DeviceController_ReceiveTriggeredRequest(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object DeviceController_ReceiveTriggeredRequest_TO_DeviceController_Proxy_ReceiveTriggeredRequest(object transformFrom) {
            return _cachedInstance2;
        }
        
        private static global::DeviceController.Proxy.DeviceControllerStateRequest _cachedInstance4 = new global::DeviceController.Proxy.DeviceControllerStateRequest();
        
        private static global::DeviceController.DeviceControllerStateRequest _cachedInstance3 = new global::DeviceController.DeviceControllerStateRequest();
        
        public static object DeviceController_Proxy_DeviceControllerStateRequest_TO_DeviceController_DeviceControllerStateRequest(object transformFrom) {
            return _cachedInstance3;
        }
        
        public static object DeviceController_DeviceControllerStateRequest_TO_DeviceController_Proxy_DeviceControllerStateRequest(object transformFrom) {
            return _cachedInstance4;
        }
    }
}
