//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("DeviceController")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("DeviceController")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="DeviceController.Y2020.M01, Version=1.0.0.0, Culture=neutral, PublicKeyToken=db89" +
    "f9e070779560")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace DeviceController.Proxy {
    
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html", ElementName="DeviceControllerState")]
    public class DeviceControllerState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public DeviceControllerState() {
        }
        
        private string _Name;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Device name")]
        public string Name {
            get {
                return this._Name;
            }
            set {
                this._Name = value;
            }
        }
        
        private bool _Active;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.DescriptionAttribute("Device state")]
        public bool Active {
            get {
                return this._Active;
            }
            set {
                this._Active = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current DeviceControllerState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::DeviceController.Proxy.DeviceControllerState typedTarget = ((global::DeviceController.Proxy.DeviceControllerState)(target));
            typedTarget._Name = this._Name;
            typedTarget._Active = this._Active;
        }
        
        /// <summary>
        ///Clones DeviceControllerState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::DeviceController.Proxy.DeviceControllerState target0 = new global::DeviceController.Proxy.DeviceControllerState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current DeviceControllerState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._Name == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Name);
            }
            writer.Write(this._Active);
        }
        
        /// <summary>
        ///Deserializes DeviceControllerState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized DeviceControllerState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                this._Name = reader.ReadString();
            }
            this._Active = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html", ElementName="ReceiveUpdatesRequest")]
    public class ReceiveUpdatesRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ReceiveUpdatesRequest() {
        }
        
        public ReceiveUpdatesRequest(string name, int count) {
            this._Name = name;
            this._Count = count;
        }
        
        private string _Name;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::Microsoft.Dss.Core.Attributes.DataMemberConstructorAttribute(Order=1)]
        public string Name {
            get {
                return this._Name;
            }
            set {
                this._Name = value;
            }
        }
        
        private int _Count;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        [global::Microsoft.Dss.Core.Attributes.DataMemberConstructorAttribute(Order=2)]
        public int Count {
            get {
                return this._Count;
            }
            set {
                this._Count = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current ReceiveUpdatesRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::DeviceController.Proxy.ReceiveUpdatesRequest typedTarget = ((global::DeviceController.Proxy.ReceiveUpdatesRequest)(target));
            typedTarget._Name = this._Name;
            typedTarget._Count = this._Count;
        }
        
        /// <summary>
        ///Clones ReceiveUpdatesRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::DeviceController.Proxy.ReceiveUpdatesRequest target0 = new global::DeviceController.Proxy.ReceiveUpdatesRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ReceiveUpdatesRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            if ((this._Name == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Name);
            }
            writer.Write(this._Count);
        }
        
        /// <summary>
        ///Deserializes ReceiveUpdatesRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ReceiveUpdatesRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            if ((reader.ReadByte() != 0)) {
                this._Name = reader.ReadString();
            }
            this._Count = reader.ReadInt32();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html", ElementName="ReceiveNormalRequest")]
    public class ReceiveNormalRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ReceiveNormalRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current ReceiveNormalRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::DeviceController.Proxy.ReceiveNormalRequest typedTarget = ((global::DeviceController.Proxy.ReceiveNormalRequest)(target));
        }
        
        /// <summary>
        ///Clones ReceiveNormalRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::DeviceController.Proxy.ReceiveNormalRequest target0 = new global::DeviceController.Proxy.ReceiveNormalRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ReceiveNormalRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes ReceiveNormalRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ReceiveNormalRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html", ElementName="ReceiveTriggeredRequest")]
    public class ReceiveTriggeredRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public ReceiveTriggeredRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current ReceiveTriggeredRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::DeviceController.Proxy.ReceiveTriggeredRequest typedTarget = ((global::DeviceController.Proxy.ReceiveTriggeredRequest)(target));
        }
        
        /// <summary>
        ///Clones ReceiveTriggeredRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::DeviceController.Proxy.ReceiveTriggeredRequest target0 = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current ReceiveTriggeredRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes ReceiveTriggeredRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized ReceiveTriggeredRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.tempuri.org/2020/01/devicecontroller.html", ElementName="DeviceControllerStateRequest")]
    public class DeviceControllerStateRequest : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public DeviceControllerStateRequest() {
        }
        
        /// <summary>
        ///Copies the data member values of the current DeviceControllerStateRequest to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::DeviceController.Proxy.DeviceControllerStateRequest typedTarget = ((global::DeviceController.Proxy.DeviceControllerStateRequest)(target));
        }
        
        /// <summary>
        ///Clones DeviceControllerStateRequest
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::DeviceController.Proxy.DeviceControllerStateRequest target0 = new global::DeviceController.Proxy.DeviceControllerStateRequest();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current DeviceControllerStateRequest to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
        }
        
        /// <summary>
        ///Deserializes DeviceControllerStateRequest
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized DeviceControllerStateRequest</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            return this;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Get : global::Microsoft.Dss.ServiceModel.Dssp.Get<global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType, global:: Microsoft.Ccr.Core.PortSet<global::DeviceController.Proxy.DeviceControllerState, global:: W3C.Soap.Fault>> {
        
        public Get() {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body) {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, global::Microsoft.Ccr.Core.PortSet<global::DeviceController.Proxy.DeviceControllerState, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class ReceiveUpdates : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::DeviceController.Proxy.ReceiveUpdatesRequest, global:: Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType>> {
        
        public ReceiveUpdates() {
        }
        
        public ReceiveUpdates(global::DeviceController.Proxy.ReceiveUpdatesRequest body) : 
                base(body) {
        }
        
        public ReceiveUpdates(global::DeviceController.Proxy.ReceiveUpdatesRequest body, global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Subscribe : global::Microsoft.Dss.ServiceModel.Dssp.Subscribe<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault>> {
        
        public Subscribe() {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body) : 
                base(body) {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class ReceiveNormal : global::Microsoft.Dss.ServiceModel.Dssp.Query<global::DeviceController.Proxy.ReceiveNormalRequest, global:: Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState>> {
        
        public ReceiveNormal() {
        }
        
        public ReceiveNormal(global::DeviceController.Proxy.ReceiveNormalRequest body) : 
                base(body) {
        }
        
        public ReceiveNormal(global::DeviceController.Proxy.ReceiveNormalRequest body, global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class ReceiveTriggered : global::Microsoft.Dss.ServiceModel.Dssp.Query<global::DeviceController.Proxy.ReceiveTriggeredRequest, global:: Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState>> {
        
        public ReceiveTriggered() {
        }
        
        public ReceiveTriggered(global::DeviceController.Proxy.ReceiveTriggeredRequest body) : 
                base(body) {
        }
        
        public ReceiveTriggered(global::DeviceController.Proxy.ReceiveTriggeredRequest body, global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class DeviceControllerOperations : global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup, global:: Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop, global:: DeviceController.Proxy.Get, global:: DeviceController.Proxy.ReceiveUpdates, global:: DeviceController.Proxy.Subscribe, global:: DeviceController.Proxy.ReceiveNormal, global:: DeviceController.Proxy.ReceiveTriggered> {
        
        public DeviceControllerOperations() {
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup() {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop() {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::DeviceController.Proxy.DeviceControllerState, global:: W3C.Soap.Fault> Get() {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            global::DeviceController.Proxy.Get operation = new global::DeviceController.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(out global::DeviceController.Proxy.Get operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            operation = new global::DeviceController.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::DeviceController.Proxy.DeviceControllerState, global:: W3C.Soap.Fault> Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            global::DeviceController.Proxy.Get operation = new global::DeviceController.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, out global::DeviceController.Proxy.Get operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            operation = new global::DeviceController.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType> ReceiveUpdates(string name, int count) {
            global::DeviceController.Proxy.ReceiveUpdatesRequest body = new global::DeviceController.Proxy.ReceiveUpdatesRequest(name, count);
            global::DeviceController.Proxy.ReceiveUpdates operation = new global::DeviceController.Proxy.ReceiveUpdates(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveUpdates(string name, int count, out global::DeviceController.Proxy.ReceiveUpdates operation) {
            global::DeviceController.Proxy.ReceiveUpdatesRequest body = new global::DeviceController.Proxy.ReceiveUpdatesRequest(name, count);
            operation = new global::DeviceController.Proxy.ReceiveUpdates(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType> ReceiveUpdates(global::DeviceController.Proxy.ReceiveUpdatesRequest body) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveUpdatesRequest();
            }
            global::DeviceController.Proxy.ReceiveUpdates operation = new global::DeviceController.Proxy.ReceiveUpdates(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveUpdates(global::DeviceController.Proxy.ReceiveUpdatesRequest body, out global::DeviceController.Proxy.ReceiveUpdates operation) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveUpdatesRequest();
            }
            operation = new global::DeviceController.Proxy.ReceiveUpdates(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            global::DeviceController.Proxy.Subscribe operation = new global::DeviceController.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, out global::DeviceController.Proxy.Subscribe operation, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            operation = new global::DeviceController.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            global::DeviceController.Proxy.Subscribe operation = new global::DeviceController.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, out global::DeviceController.Proxy.Subscribe operation, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            operation = new global::DeviceController.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> ReceiveNormal() {
            global::DeviceController.Proxy.ReceiveNormalRequest body = new global::DeviceController.Proxy.ReceiveNormalRequest();
            global::DeviceController.Proxy.ReceiveNormal operation = new global::DeviceController.Proxy.ReceiveNormal(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveNormal(out global::DeviceController.Proxy.ReceiveNormal operation) {
            global::DeviceController.Proxy.ReceiveNormalRequest body = new global::DeviceController.Proxy.ReceiveNormalRequest();
            operation = new global::DeviceController.Proxy.ReceiveNormal(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> ReceiveNormal(global::DeviceController.Proxy.ReceiveNormalRequest body) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveNormalRequest();
            }
            global::DeviceController.Proxy.ReceiveNormal operation = new global::DeviceController.Proxy.ReceiveNormal(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveNormal(global::DeviceController.Proxy.ReceiveNormalRequest body, out global::DeviceController.Proxy.ReceiveNormal operation) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveNormalRequest();
            }
            operation = new global::DeviceController.Proxy.ReceiveNormal(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> ReceiveTriggered() {
            global::DeviceController.Proxy.ReceiveTriggeredRequest body = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
            global::DeviceController.Proxy.ReceiveTriggered operation = new global::DeviceController.Proxy.ReceiveTriggered(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveTriggered(out global::DeviceController.Proxy.ReceiveTriggered operation) {
            global::DeviceController.Proxy.ReceiveTriggeredRequest body = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
            operation = new global::DeviceController.Proxy.ReceiveTriggered(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<global::DeviceController.Proxy.DeviceControllerState> ReceiveTriggered(global::DeviceController.Proxy.ReceiveTriggeredRequest body) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
            }
            global::DeviceController.Proxy.ReceiveTriggered operation = new global::DeviceController.Proxy.ReceiveTriggered(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice ReceiveTriggered(global::DeviceController.Proxy.ReceiveTriggeredRequest body, out global::DeviceController.Proxy.ReceiveTriggered operation) {
            if ((body == null)) {
                body = new global::DeviceController.Proxy.ReceiveTriggeredRequest();
            }
            operation = new global::DeviceController.Proxy.ReceiveTriggered(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DescriptionAttribute("DeviceController service (no description provided)")]
    [global::System.ComponentModel.DisplayNameAttribute("DeviceController")]
    public class Contract {
        
        public const string Identifier = "http://schemas.tempuri.org/2020/01/devicecontroller.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.tempuri.org/2020/01/devicecontroller.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.tempuri.org/2020/01/devicecontroller.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.DeviceControllerOperations = new global::DeviceController.Proxy.DeviceControllerOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.DeviceControllerOperations, "http://schemas.tempuri.org/2020/01/devicecontroller.html", "DeviceControllerOperations", ""));
        }
        
        public global::DeviceController.Proxy.DeviceControllerOperations DeviceControllerOperations;
    }
}
