//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;
using Microsoft.Dss.Core.DsspHttp;

using controller = Robotics.ZWave.Controller;
using System.ComponentModel;


namespace Robotics.ZWave.Controller
{
    
    
    /// <summary>
    /// Zwavecontroller Contract class
    /// </summary>
    public sealed class Contract
    {
        
        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember()]
        public const String Identifier = "http://house.robot/2008/05/zwavecontroller.html";
    }

    /// <summary>
    /// The Zwavecontroller State
    /// </summary>
    [DataContract]
    public class ZWaveControllerState
    {
    }

    /// <summary>
    /// Zwavecontroller Main Operations Port
    /// </summary>
    [ServicePort()]
    public class ZWaveControllerOperations :
        PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, HttpGet, HttpPost, SetDeviceLevel, DeviceOff, DeviceOn>
    {
    }

    /// <summary>
    /// Zwavecontroller Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<ZWaveControllerState, Fault>>
    {

        /// <summary>
        /// Zwavecontroller Get Operation
        /// </summary>
        public Get()
        {
        }

        /// <summary>
        /// Zwavecontroller Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) :
            base(body)
        {
        }

        /// <summary>
        /// Zwavecontroller Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<ZWaveControllerState, W3C.Soap.Fault> responsePort) :
            base(body, responsePort)
        {
        }
    }

    [DataContract]
    public class SetDeviceLevelRequest
    {
        [DataMember]
        [DataMemberConstructor]
        public byte Id;

        [DataMember]
        [DataMemberConstructor]
        public byte Level;
    }

    [Description("Set the dim level")]
    public class SetDeviceLevel : Update<SetDeviceLevelRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
    }

    [DataContract]
    public class DeviceOnRequest
    {
        [DataMember]
        [DataMemberConstructor]
        public byte Id;
    }

    [Description("Turn device on")]
    public class DeviceOn : Update<DeviceOnRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
    }

    [DataContract]
    public class DeviceOffRequest
    {
        [DataMember]
        [DataMemberConstructor]
        public byte Id;
    }

    [Description("Turn device off")]
    public class DeviceOff : Update<DeviceOffRequest, PortSet<DefaultUpdateResponseType, Fault>>
    {
    }
}
