//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     DSS Runtime Version: 2.0.730.3
//     CLR Runtime Version: 2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;

using emailsender = Robotics.EmailSender;


namespace Robotics.EmailSender
{


    /// <summary>
    /// EmailSender Contract class
    /// </summary>
    public sealed class Contract
    {

        /// <summary>
        /// The Dss Service contract
        /// </summary>
        [DataMember]
        public const String Identifier = "http://house.robot/2008/05/emailsender.html";
    }

    /// <summary>
    /// The EmailSender State
    /// </summary>
    [DataContract]
    public class EmailSenderState
    {
        [DataMember]
        [DataMemberConstructor]
        public string Host;

        [DataMember]
        [DataMemberConstructor]
        public int Port;

        [DataMember]
        [DataMemberConstructor]
        public string UserName;

        [DataMember]
        [DataMemberConstructor]
        public string Password;

        [DataMember]
        [DataMemberConstructor]
        public bool EnableSsl;
    }

    /// <summary>
    /// EmailSender Main Operations Port
    /// </summary>
    [ServicePort]
    public class EmailSenderOperations : PortSet<DsspDefaultLookup, DsspDefaultDrop, Get, SendMessage>
    {
    }

    /// <summary>
    /// EmailSender Get Operation
    /// </summary>
    public class Get : Get<GetRequestType, PortSet<EmailSenderState, Fault>>
    {

        /// <summary>
        /// EmailSender Get Operation
        /// </summary>
        public Get()
        {
        }

        /// <summary>
        /// EmailSender Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) :
            base(body)
        {
        }

        /// <summary>
        /// EmailSender Get Operation
        /// </summary>
        public Get(Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, Microsoft.Ccr.Core.PortSet<EmailSenderState, W3C.Soap.Fault> responsePort) :
            base(body, responsePort)
        {
        }
    }


    /// <summary>
    /// Make To and CC arrays...
    /// </summary>
    [DataContract]
    public class MailMessageContents
    {
        [DataMember]
        [DataMemberConstructor(Order = 1)]
        public List<string> To;

        [DataMember]
        [DataMemberConstructor(Order = 2)]
        public string From;

        [DataMember]
        [DataMemberConstructor(Order = 3)]
        public List<string> CC;

        [DataMember]
        [DataMemberConstructor(Order = 4)]
        public string Subject;

        [DataMember]
        [DataMemberConstructor(Order = 5)]
        public string Message;
    }

    public class SendMessage : Submit<MailMessageContents, PortSet<DefaultSubmitResponseType, Fault>>
    {
    }
}
